### ISSUE TITLE
Discrepancy between example and current version of Curifactory

### ISSUE THREAD

**Issue by stewartsl** [ORNL/curifactory#2]
**Describe the bug**
In the newsgroups example one stage has 

```python
@cf.stage(
    inputs=None, outputs=["training_data", "testing_data"], cachers=[PickleCacher] * 2
)
```

but this returns the following error in production

```
ERROR - InputSignatureError - Signature for 'stage_name' does not match stage input list. Signature should include [], or there may be missing default values for a stage called with suppress_missing_inputs.
```

**To Reproduce**
1. Run the example script for newsgroups
2. error should appear
3. change to input=[] instead of None
4. error should resolve

**Expected behavior**
Either change the example to be consistent with current curifactory or ensure "None" is acceptable

**Comment by WildfireXIII** [comment]
Hmm, I'm having troubles reproducing: I already have test cases that explicitly verify that an `inputs=None` passes, and I'm also able to run the example newsgroups script (executing `experiment newsgroups`  inside `examples/minimal/`) without error. 

There might be a somewhat unrelated error that's causing this for your example, `InputSignatureError` will result from any `TypeError` (see reference below) that occurs in the actual stage function call. Was there a `Sub error: (...)` string that was in the output? Could you grab the whole stack trace from the exception for me, if you get a chance? This error could potentially result if the stage is being called incorrectly e.g. I think if you were passing any parameters manually where it isn't expecting any.

Relevant lines for reference, a sub error of some form should print at the end: https://github.com/ORNL/curifactory/blob/f8be235b7fa7b91cc86f61d610d7093075b89d1f/curifactory/staging.py#L320-L325

**Comment by WildfireXIII** [comment]
I'm closing this for now, feel free to re-open if you revisit this
