### ISSUE TITLE
Curifactory --store-full runs may not grab all artifacts if they are previously cached

### ISSUE THREAD

**Issue by stewartsl** [ORNL/curifactory#32]
**Describe the bug**
Curifactory does not appear to store previously cached artifacts if --store-full is run on an experiment a second time with overwrite specified for one more more stages. Instead only the artifacts from the overwritten stages appear to make it into the store-full folder.

**To Reproduce**
1. Run a --store-full run of curifactory for an experiment
2. Overwrite one stage of the experiment and run --store-full again
3. Observe that not all artifacts are included in the second store full run folder

**Expected behavior**
I would expect all artifacts needed to reproduce the run to be included in the store full folder to be included unless otherwise excluded specifically by the user.

**Comment by WildfireXIII** [comment]
Closing, this turned out to be a separate issue where a cacher inside a stage was using a `get_path` with a default `track=True` and returning that path to a stage-level FileRefCacher that had `track=False`
