### ISSUE TITLE
PandasCsvCacher should have a way to set an escapechar

### ISSUE THREAD

**Issue by stewartsl** [ORNL/curifactory#4]
**Is your feature request related to a problem? Please describe.**
When attempting to use this cacher, the error message "need to escape, but no escapechar set" occurs if dataframe values contain a comma. 

**Describe the solution you'd like**
Either create another cacher or choose an intelligent default escapechar and warn when it is used

**Describe alternatives you've considered**
Users could individually write their own cacher but this error is troublesome when a user first encounters this specific error at the end of a long computation when they did not realize some of their data contained commas.

**Comment by WildfireXIII** [comment]
I wasn't able to replicate this, but I did add a test case and fixed a related issue
