### ISSUE TITLE
Improve hashing mechanism

### ISSUE THREAD

**Issue by WildfireXIII** [ORNL/curifactory#5]
# Problem

Argument hashes, used for caching and determining cache hits/misses, are currently computed in an ineffective way - they are done by taking a string representation of the dataclass dictionary of the arguments instance, and computing an md5 hash: 

https://github.com/ORNL/curifactory/blob/dce202ddeb82d0e58c03752e0f27444b72a91e82/curifactory/utils.py#L425-L434

This causes several problems:

1. Changing operational arguments (e.g. number of GPU's to run on etc.) that shouldn't change actual computed values will still cause a cache miss. (You can currently get around this by setting the operational arguments directly inside the experiment's `run` at which point the hash has already been calculated, but this rather defeats the purpose of arguments)
2. The default string representation for many complex objects is not always unique/does not always reflect whatever arguments they were initialized with, leading to incorrect cache hits.
3. The default string representation for some objects (typically callables) is just the pointer address, leading to perpetual cache misses even if the object was equivalent to a previous run.
4. If arguments are added onto an argument dataclass later on, even when unused and unset in an older experiment/parameter files, it will still make old `store-full` runs cache miss on everything. (You would ordinarily get around this by checking out the git commit associated with that experiment run, but this can still be inconvenient in other instances. For example, during development if you add a new argument for a separate experiment, but in the process invalidate all your current cached values from another working experiment.)
5. There's no effective way to modify how any of this is done from the user's perspective.

# Proposed solution

NOTE: Not sold on explicitly using `__hash__` versus just adding a `get_hash()` to the `ExperimentArgs` class or similar - the existing `hash()` and `__hash__` carries some baggage and may imply immutability where not necessarily required: https://stackoverflow.com/questions/53990296/how-do-i-make-a-python-dataclass-inherit-hash. (e.g. you can't hash a dictionary, you have to hash the string of the dictionary) (also see discussion in `unsafe_hash` below https://docs.python.org/3/library/dataclasses.html#module-contents)

* `ExperimentArgs` should define a dictionary `hashing_functions` that the user can manipulate, where keys refer to the arguments, and the values are a callable that take the value of the argument (or None in order to exclude from hash)

* ExperimentArgs overrides the `__hash__` function (which the `utils.get_hash()` should then use), and by default does a few things:
    1. Call `asdict` on itself and take the list of keys as "things that need to be hashed"
    2. Make a `complete_hashing_functions` dictionary that is initially filled with every key from step 1 and some default function that will naively compute a hash that will work for most cases (something like `lambda x: hash(x) if x.__hash__ is not None else hash(str(x))`)
    3. Keys that a priori need to be ignored (`hash`, `overwrite`) get set to `None` in `complete_hashing_functions`
    4. `complete_hashing_functions` is updated with `hashing_functions`, allowing the user to override the hashing mechanism for any parameters
    5. The hashes are all computed and combined in some way and returned.
* Optionally, the user can override their subclasses `__hash__` functions to completely customize how it's done for a particular args class
* Helper functions could be provided to set `hashing_functions` quickly, e.g. `hashing_functions = ignore_all_except("thing_i_care_about1", "thing_i_care_about2")` etc.
* Various checks could improve the default hashing function, e.g. hashing `qualname` on anything that is a callable

* Anything that is None or returns None _does not get included in the hash_ (which should fix problem 4)

**Comment by jasonmhite** [comment]
So this seems ok, but I will observe that you should try to hide implementation details like having to implement hashing functions as much as humanly possible. To the point that I personally think it's better to sacrifice having "perfect" detection of changes if it makes it so that you can avoid having to think about this as a user.

**Comment by WildfireXIII** [comment]
That's a good point, I think importantly this wouldn't _require_ a user to do anything with regards to hashing, the default functionality in the parent `ExperimentArgs` class should still be vaguely equivalent to what's done currently (with some more smarts), this would just allow changing the "unique representations" of specific parameters, and also allow customizing what parameters are ignored for caching purposes
