### ISSUE TITLE
Curifactory logger might be eating my logging settings?

### ISSUE THREAD

**Issue by deniederhut** [ORNL/curifactory#80]
**Describe the bug**
When trying to log warnings or errors inside a stage, they do not show up in the logfile as expected.

**To Reproduce**

Running the following script:

```python
from dataclasses import dataclass
from logging import getLogger

from curifactory import ArtifactManager, ExperimentParameters, Record, stage
from curifactory.caching import Lazy, PickleCacher

LOGGER = getLogger(__name__)

@dataclass
class MyParams(ExperimentParameters):
    number: float = 1.0

@stage(inputs=None, outputs=[Lazy("initial_value")], cachers=[PickleCacher])
def get_initial_value(record):
    my_value = 5
    LOGGER.error("THIS IS A LOG MESSAGE")
    return my_value * record.params.number

@stage(inputs=["initial_value"], outputs=["final_value"], cachers=[PickleCacher])
def multiply_again(record, initial_value):
    return initial_value * record.params.number


if __name__ == '__main__':
    from logging import basicConfig
    basicConfig(filename='this.log')
    manager = ArtifactManager("experiment_one")
    param_grid = [MyParams(number=number) for number in (0, 1, 2, 2)]
    for param in param_grid:
        record = Record(manager, param)
        result = multiply_again(get_initial_value(record))
    manager.generate_report()
```

results in an empty file called `this.log`.

**Expected behavior**
I expected to see three error messages that read `THIS IS A LOG MESSAGE`.

**Comment by WildfireXIII** [comment]
Oh this is interesting, I've never actually tried doing that! I'll note that Curifactory is setting up it's own logging through `utils.init_logging()`:
https://github.com/ORNL/curifactory/blob/1944701a1f29cec00ad9152b2ee6ae76310b3854/curifactory/utils.py#L354-L439
with the intent that you can just directly call `logging.info()`, `logging.error()` etc. without having to worry about setting up your own loggers. But, I could see where someone might want to have their own specific logging infrastructure in addition, e.g. log to specific files and so on.

I believe this little bugger in that function is what's actually doing the eating:
https://github.com/ORNL/curifactory/blob/1944701a1f29cec00ad9152b2ee6ae76310b3854/curifactory/utils.py#L429-L432
which always felt a little dirty, but I remember being particularly annoyed at some libraries for being really noisy in their logging, and not wanting to have to individually disable specific loggers every time I wrote an experiment.

At the very least, I could add a config item (or manager argument more likely) for whether curifactory silences all non-curifactory loggers or not. Another option would be to make it so curifactory isn't co-opting the root logger and uses its own, likely meaning if you want to output directly to curifactory logs you'd probably need to do something like

```python
from curifactory import logging as log

...
log.info("something curifactory related"
```

I think I prefer the first option, I like curifactory making it easy by default to just have a sane logging setup, but I'll discuss it with my team

**Comment by WildfireXIII** [comment]
An `--all-loggers` flag has been added to address quieting external library logs. The issue brought up here specifically was actually due to curifactory resetting the handlers on the root logger whenever `init_logging` is called. There's perhaps a more elegant way to solve this that will require a lot more work (and would be part of #101) but until then, it's enough to add any additional handlers or override the root logger after the manager has been created, as seen in my slightly modified version of your example: https://github.com/ORNL/curifactory/blob/main/examples/experiments/manual.py
