### ISSUE TITLE
Rendering of SciPy title in references section of paper

### ISSUE THREAD

**Issue by deniederhut** [ORNL/curifactory#87]
In the rendered PDF, I see the conference name showing up in lower case

<img width="617" alt="Screenshot 2023-10-02 at 6 40 58 PM" src="https://github.com/ORNL/curifactory/assets/6868396/0fda91d0-7a90-4b74-8997-a6a3c2d53f7a">

Would it be possible to change this line here:

https://github.com/ORNL/curifactory/blob/b35d8744fc05ee019e2386676e04e46a3563bc2e/paper/paper.bib#L44

to `{P}ython in {S}cience {C}onference`?

**Comment by stewartsl** [comment]
@WildfireXIII I don't appear to have permissions to get the editorbot to generate the scipy paper draft in our review. Can you take a shot to verify the issue is fixed? I addressed this and other capitalization issues I noted in our bib in the referenced commit.

**Comment by stewartsl** [comment]
![Screenshot 2023-10-02 at 11 45 47 PM](https://github.com/ORNL/curifactory/assets/19293911/22439992-798e-4b2c-94f9-3a5df8197fdd)

Fixed this and other capitalization issues in the recent commit.
