### ISSUE TITLE
Default artifact manager in procedure generates empty report

### ISSUE THREAD

**Issue by deniederhut** [ORNL/curifactory#89]
**Describe the bug**
When using the Procedure class to run stages, and not instantiating and passing a manager, the HTML report is empty.

**To Reproduce**
This experiment definition

```
from dataclasses import dataclass

from curifactory import ArtifactManager, Record, Procedure, stage
from curifactory.caching import Lazy, PickleCacher


@stage(inputs=None, outputs=[Lazy("initial_value")], cachers=[PickleCacher])
def get_initial_value(record):
    my_value = 5
    return my_value * record.params.number

@stage(inputs=["initial_value"], outputs=["final_value"], cachers=[PickleCacher])
def multiply_again(record, initial_value):
    return initial_value * record.params.number


def run(param_sets, manager):
    proc = Procedure([
        get_initial_value,
        multiply_again
    ])
    for param_set in param_sets:
        proc.run(param_set)
```

run with `experiment run -p basic_params` appears to succeed, but the HTML report that gets generated is empty:

<img width="447" alt="Screenshot 2023-10-02 at 7 31 44 PM" src="https://github.com/ORNL/curifactory/assets/6868396/74a7b415-e6c3-48b4-b729-ac7491c5eac6">

**Expected behavior**
Passing in the manager class given to the run function results in the following

<img width="876" alt="Screenshot 2023-10-02 at 7 32 28 PM" src="https://github.com/ORNL/curifactory/assets/6868396/ec06e5da-c7a6-4346-9204-6adfb85f76c4">

**Comment by WildfireXIII** [comment]
Another good catch, I forgot this was ever a thing - the artifact manager that procedure initializes has no connection to the outer one, and the outer one is the one generating the report. There's no non-horrific way of solving this that I'm aware of, and honestly I think it's of pretty limited value to have a pure-default artifact manager automatically initialized anyway, so I'm going to remove the default `manager=None` and associated logic

**Comment by WildfireXIII** [comment]
Note that I actually addressed this by allowing the `.run()` function to take a manager and records list, and of course removing the auto init of an artifact manager in `__init__` if manager is `None`. The advantage of this is someone can define procedures in some nice re-usable location, and have  it not (yet) associated with any manager, so an experiment run function could then pull it in and set the manager on it at that point.
